#include<stdio.h>
#include<conio.h>
void main()
{
    int i;
    printf("a\tb\tc\td\te\tf\tg\th\ti\tj\tk\tl\tm\tn\to\n");
    for(i=1;i<=15;i++)
    {
        printf("%d\t",i);
    }
    printf("\n");
    printf("p\tq\tr\ts\tt\tu\tv\tw\tx\ty\tz\n");
    for(i=16;i<=26;i++)
    {
        printf("%d\t",i);
    }
    printf("\n\n");
        printf("A\tB\tC\tD\tE\tF\tG\tH\tI\tJ\tK\tL\tM\tN\tO\n");
    for(i=27;i<=41;i++)
    {
        printf("%d\t",i);
    }
    printf("\n");
    printf("P\tQ\tR\tS\tT\tU\tV\tW\tX\tY\tZ\n");
    for(i=42;i<=52;i++)
    {
        printf("%d\t",i);
    }
    getch();
}
